import './globals.css'
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import NavBar from './components/NavBar'
import { Theme, ThemePanel } from '@radix-ui/themes';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <NavBar></NavBar>
          <main>{children}</main>
          <ThemePanel />
        </Theme>
      </body>
    </html>
  )
}
