import "./theme-config.css";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Container, Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NavBar } from './components';
import { PropsWithChildren } from "react";
import AuthProvider from "./providers/AuthProvider";


export const metadata: Metadata = {
  title: 'Issue Tracker',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <AuthProvider>
          <Theme>
            {/* <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%"> */}
            <NavBar />
            <main className='pl-5'>
              <Container>
                {children}
              </Container>
            </main>
            {/* <ThemePanel /> */}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
